; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv64 -mattr=xposit -O0 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s  -check-prefix=RV64Xposit

declare void @llvm.riscv.qclr()

define void @qclr() nounwind {
; RV64Xposit-LABEL: qclr:
; RV64Xposit:       # %bb.0:
; RV64Xposit-NEXT:    qclr.s
; RV64Xposit-NEXT:    ret
  tail call void @llvm.riscv.qclr()
  ret void
}