// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64 -target-feature +xposit -emit-llvm %s -o - \
// RUN:     | FileCheck %s  -check-prefix=RV64Xposit

// RV64Xposit-LABEL: @qclr(
// RV64Xposit-NEXT:  entry:
// RV64Xposit-NEXT:    call void @llvm.riscv.qclr()
// RV64Xposit-NEXT:    ret void
//
void qclr() {
    __builtin_riscv_qclr();
}